### ISSUE TITLE
C段扫描不够准确

### ISSUE THREAD

**Issue by lalaguo** [1n7erface/RequestTemplate#10]
C段扫描不够准确，有些ip没有被存活扫描出来

**Comment by lalaguo** [comment]
对的是在使用VPN的情况下发生的，加VX的话wxid_oarqkis5rwl922
谢谢师傅了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 下午4:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1n7erface/RequestTemplate] C段扫描不够准确 (Issue #10)





 
请问是低权限的情况下还是高权限的情况下，在低权限下确实存在这个问题，不过是很特殊的环境。可以加vx复现下吗？

**Comment by 1n7erface** [comment]
你加我吧，你的我加不上。VX:In7erface
