### ISSUE TITLE
能否打包添加一个win32可执行文件

### ISSUE THREAD

**Issue by ZyRooting** [1n7erface/RequestTemplate#12]

**Comment by 1n7erface** [comment]
经过我的大量努力，发现golang的embed表达式需要1.16以上版本，而兼容xp和03的需要1.10-1.13版本之间。所以版本冲突暂无法解决此问题。在后续版本我会持续努力。

**Comment by ZyRooting** [comment]
> 经过我的大量努力，发现golang的embed表达式需要1.16以上版本，而兼容xp和03的需要1.10-1.13版本之间。所以版本冲突暂无法解决此问题。在后续版本我会持续努力。

也可以考虑开发基于socks代理下的内网扫描，实战性会更好

**Comment by 1n7erface** [comment]
我认为这款工具的定位就在于最小的发包量和卡顿解决内网的利用以及扫描问题，经过socks扫描与此工具的初衷有所背离。而且我认为所有的权限，都可以将客户端上传且运行。
