### ISSUE TITLE
虚拟环境下 存活网段扫描不准确

### ISSUE THREAD

**Issue by ttstormxx** [1n7erface/RequestTemplate#14]
vmware虚拟机上运行app.exe，会显示大部分网段都存活，选择一个不存在的网段扫描，会扫出多个不存在的IP，且每个IP均有8000、8099等端口开放，web扫描状态码200或者401，但实际上不存在

**Comment by 1n7erface** [comment]
这种情况应该不存在，因为端口都扫出来了，我这边的建议是扫出来的端口和web服务手动通过浏览器访问看看。把访问的截图还有扫描的截图贴上来，对此bug进行修改。

**Comment by ttstormxx** [comment]
确认了一下是虚拟机NAT的问题，不是工具问题。

**Comment by 1n7erface** [comment]
好的，感谢反馈和对本工具的支持。
