### ISSUE TITLE
macos Ventura V13.0运行失败

### ISSUE THREAD

**Issue by H4wk-eye** [1n7erface/RequestTemplate#19]
segmentation fault ./App_darwin -h

**Comment by 1n7erface** [comment]
mac更新之后确实有这个问题，跟软件没关系，你可以尝试下新发布的没压缩的试试。

**Comment by H4wk-eye** [comment]
能发布一版amd没压缩的版本吗，新发布的App是arm架构的

**Comment by 1n7erface** [comment]
发了，建议先看下readme，macos有点坑。
