### ISSUE TITLE
可以扫B段吗

### ISSUE THREAD

**Issue by Po3son** [1n7erface/RequestTemplate#2]
可以扫B段吗

**Comment by 1n7erface** [comment]
不支持扫b段，以为扫描/16或者/8意味这梭哈，本工具提供的-c 192 -c 10 -c 172会网段连通性探测然后进行扫描与b段道理相同甚至更优雅。如果此需求提出人数过多将会在后期补充,谢谢提交

**Comment by 1n7erface** [comment]
不支持扫b段，因为扫描/16或者/8意味着梭哈，本工具提供的-c 192 -c 10 -c 172会进行网段连通性探测然后进行扫描与b段道理相同甚至更优雅。如果此需求提出人数过多将会在后期补充,谢谢提交。

**Comment by 1n7erface** [comment]
已经支持CIDR网段计算方式，参数-i ，此issues结束。
