### ISSUE TITLE
你好，请问RequestTemplate.jar在哪呀？

### ISSUE THREAD

**Issue by wukai230** [1n7erface/RequestTemplate#22]
是暂时下线了吗还是我没找到

**Comment by 1n7erface** [comment]
在往期的发行版本中可以找到，最起码四个版本之前了。我花了大量的精力一直在完善扫描端，直到这个版本我才认为它相对完美。关于jar的Java端，我一直也想彻头彻尾的去重构，让它更加的出色。但是我认为我目前没有更好的想法对它进行深度重构，还有懒的原因。所以如果你对这个项目有一些期望或者认同，就等等吧。或许在某一天我会心血来潮重构Java端，相信那一天不会很远。但至少现在扫描端我认为它完全出色，你可以试试。
