### ISSUE TITLE
请问下m1 mac版的怎么使用darwin的呢

### ISSUE THREAD

**Issue by PikkA-bb** [1n7erface/RequestTemplate#4]

**Comment by PikkA-bb** [comment]
darwin下载后该怎么运行呢？该使用哪个命令呢？下载打开显示unicode（utf-8）无法打开

**Comment by PikkA-bb** [comment]
终端为zsh版本的

**Comment by PikkA-bb** [comment]
请问下是装了什么环境么

**Comment by 1n7erface** [comment]
可以提供截图嘛？

**Comment by PikkA-bb** [comment]
<img width="701" alt="图片" src="https://user-images.githubusercontent.com/75553451/164503437-8ef091ee-3e96-44b9-9b93-2a25b7e5c7e3.png">
<img width="368" alt="图片" src="https://user-images.githubusercontent.com/75553451/164503570-cd57a5ec-be8e-4456-a5b8-70a7d8c15231.png">

**Comment by 1n7erface** [comment]
你的使用方法不对，首先给权限,chmod a+x App_darwin.其次使用 ./App_darwin -i 192.168.1.1/24
