### ISSUE TITLE
jar包出现异常

### ISSUE THREAD

**Issue by PikkA-bb** [1n7erface/RequestTemplate#5]
错误: 找不到或无法加载主类 com.ln7erface.App
原因: java.lang.NoClassDefFoundError: javafx/application/Application
请问下怎么处理呢

**Comment by 1n7erface** [comment]
这是你的java版本的问题，java端使用的ui为fx，支持jdk8以下。

**Comment by PikkA-bb** [comment]
请问支持jdk8么
