### ISSUE TITLE
windows界面的一点小建议

### ISSUE THREAD

**Issue by roturnd** [1n7erface/RequestTemplate#6]
java端最大化的时候中间面板右边那块，也就是命令执行的那部分，整个窗口最大化的时候没有跟着放大。。。还是小小一块得拖滚轮查看，希望能适配下。（工具非常好用，吹爆师傅！）
![@%FC BN6TP@BIIHSJVLHL2X](https://user-images.githubusercontent.com/48887149/165512852-0311076a-e2cc-4450-92d0-ff77329dbc22.png)

**Comment by 1n7erface** [comment]
谢谢，新版本已经在几分钟前已经发布请更新。在后续版本中解决当前问题，此issue将在解决后关闭。感谢支持。

**Comment by 1n7erface** [comment]
新版本已经发布，取消了用户收缩ui的权限，为了美化。
