### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by lapalipi** [1n7erface/RequestTemplate#9]
➜  Downloads ./App_darwin -i 124.233.78.0/24       

 _____                    _       _
|_   _|                  | |     | |
  | | ___ _ __ ___  _ __ | | __ _| |_ ___
  | |/ _ \ '_'  _ \| '_ \| |/ _' | __/ _ \
  | |  __/ | | | | | |_) | | (_| | ||  __/
  \_/\___|_| |_| |_| .__/|_|\__,_|\__\___|
                   | |  by 1n7erface v1.0.4
                   |_|
[=] ============icmp alive============
[=] dial ip4:icmp 127.0.0.1: socket: operation not permitted
[=] No found alive host
[=] 执行时间:1.534989904s
[=] ================================
[=] ============scan port============
[=] No found open ports
[=] 执行时间:303.693µs
[=] ================================
[=] end......
➜  Downloads

**Comment by 1n7erface** [comment]
这款工具的定位是内网的扫描工具,所有的漏洞检测都是基于icmp的检测存活。公网中的众多机器都是禁ping的导致无法发现存活IP，在内网当中却不会禁ping。感谢提交，此issues关闭。
